# Generated by Django 6.0.2 on 2026-09-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_qr/'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
