# Generated by Django 6.0.2 on 2026-09-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_survey_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Wheel / prize label', max_length=120)),
                ('win_amount', models.CharField(help_text='e.g. Rs. 100 OFF', max_length=80)),
                ('win_detail', models.CharField(blank=True, max_length=200)),
                ('promo_code', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured reward is shown when the shopper wins / claims')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='api.store')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
