# Generated by Django 6.0.2 on 2026-09-10 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_store_latitude_store_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Training', 'Training'), ('Assessed', 'Assessed'), ('Certified', 'Certified'), ('Rejected', 'Rejected'), ('Deployed', 'Deployed')], default='Pending', max_length=20)),
                ('invite_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ambassadors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.ambassador')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=40)),
                ('question_type', models.CharField(default='verbal', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.assessmentsession')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('session', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='training_videos/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('transcript', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(blank=True, max_length=200)),
                ('audio_file', models.FileField(blank=True, upload_to='assessment_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('communication_quality', models.FloatField(blank=True, null=True)),
                ('speaking_speed_wpm', models.FloatField(blank=True, null=True)),
                ('filler_rate', models.FloatField(blank=True, null=True)),
                ('nervousness_pct', models.FloatField(blank=True, null=True)),
                ('dominant_mood', models.CharField(blank=True, max_length=40)),
                ('affect_breakdown', models.JSONField(blank=True, default=dict)),
                ('speech_metrics', models.JSONField(blank=True, default=dict)),
                ('linguistic_metrics', models.JSONField(blank=True, default=dict)),
                ('question_relevance', models.JSONField(blank=True, default=dict)),
                ('video_relevance', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.assessmentquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.assessmentsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
