# Generated by Django 5.2.17 on 2026-09-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_training_ambassador_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='deployed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassadors', to='api.store'),
        ),
    ]
