# Generated by Django 5.2.17 on 2026-09-11 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_platform_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date of the shift')),
                ('day_key', models.CharField(help_text='Mon…Sun for UI week board', max_length=3)),
                ('shift_label', models.CharField(max_length=64)),
                ('peak_recommended', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Scheduled', 'Scheduled'), ('Conflict', 'Conflict')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='api.ambassador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.store')),
            ],
            options={
                'ordering': ['date', 'shift_label', 'id'],
            },
        ),
    ]
