# Generated by Django 5.2.17 on 2026-09-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shift_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='check_in_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='check_in_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='check_in_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
