# Generated by Django 5.2.17 on 2026-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shift_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideo',
            name='questions_json',
            field=models.JSONField(blank=True, default=list, help_text='HO-authored assessment questions: [{id, type, question, description}, …]'),
        ),
    ]
