# Generated by Codex on 2026-09-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_training_video_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='store',
            field=models.ForeignKey(
                blank=True,
                help_text='Leave empty only for legacy fallback questions.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='survey_questions',
                to='api.store',
            ),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.UniqueConstraint(
                fields=('store', 'order'),
                name='unique_survey_question_order_per_store',
            ),
        ),
    ]
