# Generated by Django 5.2.17 on 2026-09-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0013_store_survey_questions')]

    operations = [
        migrations.CreateModel(
            name='AmbassadorComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.ambassador')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_complaints', to='api.store')),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
