# Generated by Django 5.2.17 on 2026-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_store_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
