# Generated by Django 5.2.17 on 2026-09-28 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def group_daily_rows(apps, schema_editor):
    """Rows from the old daily upload become one monthly shift per BA, store, hours and month."""
    ShiftAssignment = apps.get_model('api', 'ShiftAssignment')
    MonthlyShift = apps.get_model('api', 'MonthlyShift')
    groups = {}
    rows = ShiftAssignment.objects.filter(
        start_time__isnull=False, end_time__isnull=False, monthly_shift__isnull=True
    ).order_by('date', 'id')
    for row in rows:
        key = (row.ambassador_id, row.store_id, row.start_time, row.end_time, row.date.strftime('%Y-%m'))
        monthly = groups.get(key)
        if monthly is None:
            monthly = MonthlyShift.objects.create(
                store_id=row.store_id,
                ambassador_id=row.ambassador_id,
                month=key[4],
                start_time=row.start_time,
                end_time=row.end_time,
                shift_label=row.shift_label,
                peak_recommended=row.peak_recommended,
                status=row.status,
                created_by_id=row.created_by_id,
            )
            groups[key] = monthly
        row.monthly_shift = monthly
        row.save(update_fields=['monthly_shift'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shift_times'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_label', models.CharField(max_length=64)),
                ('peak_recommended', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Scheduled', 'Scheduled'), ('Conflict', 'Conflict')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_shifts', to='api.ambassador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monthly_shifts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_shifts', to='api.store')),
            ],
            options={
                'ordering': ['-month', 'store__name', 'start_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='monthly_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days', to='api.monthlyshift'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('monthly_shift__isnull', False)), fields=('monthly_shift', 'date'), name='one_day_per_monthly_shift'),
        ),
        migrations.RunPython(group_daily_rows, migrations.RunPython.noop),
    ]
