# Generated by Django 5.2.17 on 2026-09-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_monthly_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='checkout_report',
            field=models.JSONField(blank=True, default=dict, help_text='Stock, sales and competitor data'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='early_checkout_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='report_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the BA submitted the checkout report (check-out counts only after this)', null=True),
        ),
    ]
