# Generated by Django 5.2.17 on 2026-09-28 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_0019_ambassadormonthtarget_0019_checkout_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.CharField(help_text='Id the app gave it, e.g. sup-lx2k9', max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(help_text='Also the sign-in name', max_length=254, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, help_text='Django password hash; empty = no login yet', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='ba_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='brand',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='client_id',
            field=models.CharField(blank=True, help_text='Id the app gave it', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='customer_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='ho_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='kind',
            field=models.CharField(choices=[('customer', 'Customer'), ('ba', 'Brand Ambassador')], default='ba', max_length=10),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='sku',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consumer',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='current_brand',
            field=models.CharField(blank=True, help_text='Tea the shopper uses now', max_length=120),
        ),
        migrations.AddField(
            model_name='consumer',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consumer',
            name='reasons',
            field=models.JSONField(blank=True, default=list, help_text='Why they chose that tea'),
        ),
        migrations.AlterField(
            model_name='ambassadorcomplaint',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.ambassador'),
        ),
        migrations.AlterField(
            model_name='ambassadorcomplaint',
            name='complaint',
            field=models.TextField(help_text='Customer complaint text, or the BA issue details', max_length=2000),
        ),
        migrations.AlterField(
            model_name='ambassadorcomplaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ba_name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('checkout', 'Checkout'), ('anytime', 'Any time'), ('excel', 'Excel upload')], max_length=10)),
                ('stock', models.JSONField(blank=True, default=dict)),
                ('sales', models.JSONField(blank=True, default=dict)),
                ('other_brands', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField()),
                ('ambassador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='api.ambassador')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='api.store')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KpiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='A store belongs to one supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='api.supervisor'),
        ),
        migrations.CreateModel(
            name='SupervisorNotification',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.supervisor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterception',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ba_name', models.CharField(max_length=120)),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=40)),
                ('city_area', models.CharField(blank=True, max_length=120)),
                ('previous_brand', models.CharField(blank=True, max_length=120)),
                ('previous_sku', models.CharField(blank=True, max_length=120)),
                ('current_sku', models.CharField(blank=True, max_length=120)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('ambassador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interceptions', to='api.ambassador')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interceptions', to='api.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyVisit',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('day', models.CharField(max_length=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('selfie', models.ImageField(upload_to='journey/')),
                ('ba_photo', models.ImageField(upload_to='journey/')),
                ('stock_photo', models.ImageField(upload_to='journey/')),
                ('completed_at', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_visits', to='api.store')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_visits', to='api.supervisor')),
            ],
            options={
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('supervisor', 'week_start', 'day', 'store'), name='one_visit_per_stop')],
            },
        ),
        migrations.CreateModel(
            name='JourneyPlan',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('week_start', models.DateField(help_text='Monday of the week')),
                ('stops', models.JSONField(default=list, help_text='[{day: "Mon", storeId: 12}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_plans', to='api.supervisor')),
            ],
            options={
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('supervisor', 'week_start'), name='one_journey_plan_per_week')],
            },
        ),
    ]
