# Generated by Django 5.2.17 on 2026-09-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_supervisor_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadormonthtarget',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_targets', to='api.store'),
        ),
    ]
