# Generated by Django 5.2.17 on 2026-09-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_target_store_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivated BAs keep their history but cannot open the app or be scheduled.'),
        ),
    ]
