# Generated by Django 5.2.17 on 2026-09-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_ambassador_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='footfall_date',
            field=models.DateField(blank=True, help_text='Day today_footfall was entered for', null=True),
        ),
        migrations.CreateModel(
            name='StoreFootfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('entered_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footfall_days', to='api.store')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('store', 'date'), name='one_footfall_per_store_day')],
            },
        ),
    ]
