# Generated by Django 5.2.17 on 2026-09-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_store_footfall'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='check_out_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='check_out_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='check_out_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
