# Generated by Django 5.2.17 on 2026-09-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_checkout_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='check_in_photo',
            field=models.ImageField(blank=True, help_text='Selfie from the face check', null=True, upload_to='checkins/'),
        ),
        migrations.CreateModel(
            name='TrainingPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('video', 'Training video question'), ('scenario', 'Practice scenario')], max_length=10)),
                ('title', models.CharField(blank=True, help_text='Training module or scenario name', max_length=200)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to='api.ambassador')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
