# Generated by Django 5.2.17 on 2026-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_ba_selfie_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='password_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted copy so Head Office can look the password up (key derived from SECRET_KEY)'),
        ),
    ]
