# Generated by Django 5.2.17 on 2026-09-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_whole_kg_target_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyvisit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeyvisit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
