# Generated by Django 5.2.17 on 2026-10-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_journey_visit_location_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City SKU',
                'ordering': ['city', 'id'],
                'constraints': [models.UniqueConstraint(fields=('city', 'sku'), name='one_sku_per_city')],
            },
        ),
    ]
