# Generated by Django 5.2.17 on 2026-10-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_city_sku'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citysku',
            name='one_sku_per_city',
        ),
    ]
