# Generated by Django 5.2.17 on 2026-10-01 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_city_sku_not_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shiftassignment',
            name='one_day_per_monthly_shift',
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('monthly_shift', 'date'), name='one_day_per_monthly_shift'),
        ),
    ]
