# Generated by Django 5.2.17 on 2026-10-05 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_userinterception_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Internal field identifier', max_length=100)),
                ('label', models.CharField(help_text='Label shown to BAs', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of option strings (for select)')),
                ('is_active', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('ALL', 'All'), ('CITY', 'City'), ('STORE', 'Store')], default='ALL', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitor_fields', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_fields', to='api.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
