# Generated by Django 5.2.17 on 2026-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_shiftassignment_attendance_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitorfieldconfig',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='competitorfieldconfig',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competitorfieldconfig',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competitorfieldconfig',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
