# Generated by Django 5.2.17 on 2026-10-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_city_sku_brand'),
        ('api', '0041_alter_competitorfieldconfig_options_and_more'),
    ]

    operations = [
    ]
