# Generated by Django 5.2.17 on 2026-10-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_mis_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterception',
            name='current_sku',
            field=models.TextField(blank=True),
        ),
    ]
