# Generated by Django 5.2.17 on 2026-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Head Office only: limits this user to one city (e.g. Lahore). Blank = every city.', max_length=100),
        ),
    ]
